### ISSUE TITLE
Add more information to results

### ISSUE THREAD

**Issue by MasterMedo** [MasterMedo/typetest#6]
It would be beneficial to know more things about the typing tests that were taken.
At the time of writing, when the user successfully finishes a typing test he is presented with a message:
```
accuracy: 100%
speed:    127wpm
duration: 1.98s
```

It would be cool to add more information:
- number of restarts
- keyboard layout used
- ...

**Comment by s-surineni** [comment]
@MasterMedo Can I work on the issue?
